version: '3.8'
services:
  postgres-db:
    image: postgres:15 
    container_name: productos_db
    restart: always
    ports:
      - "5432:5432" 
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: mysecretpassword
      POSTGRES_DB: productos_db
    volumes:
      - postgres_data:/var/lib/postgresql/data 

volumes:
  postgres_data: